
manipulator:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.01 
  kinematics_solver_attempts: 20
  mode: global
  position_scale: 1.0
  rotation_scale: 0.5
  position_threshold: 0.005
  orientation_threshold: 0.01
  # was 0.05 before
  cost_threshold: 0.005
  minimal_displacement_weight: 0.005
  # center_joints_weight: 0.001