
manipulator:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.03 
  kinematics_solver_attempts: 40
  mode: global
  position_scale: 1.0
  rotation_scale: 0.5
  #0.001 by defaults
  position_threshold: 0.005
  # 0.01 by default
  orientation_threshold: 0.05
  # was 0.005 before
  cost_threshold: 0.008
  # minimal_displacement_weight: 0.025
  minimal_displacement_weight: 0.03
  center_joints_weight: 0.001