/move_it_node:
  ros__parameters:
    # Original at 0.2 for slow testing, ~0.5rad/s kortex default
    soft_joint_speed_limit: 0.5
    time_step: 0.1
    linear_distance_thresh: 0.005
    angular_distance_thresh: 0.01