# Custom service to request grasp poses from a given point cloud
sensor_msgs/Image image
sensor_msgs/Image depth_image
sensor_msgs/Image segmentation_map
sensor_msgs/CameraInfo camera_info
---
bool success